### ISSUE TITLE
Use with a composer/pull-based D8 repo

### ISSUE THREAD

**Issue by ptmkenny** [leevh/kalabox-plugin-behat#1]
Hey, thanks for sharing this.  I tried to get Behat working on Kalabox about a year ago and didn't make any headway.

I installed the plugin, but unfortunately it doesn't work for repositories that are composer/pull-based (drupal stored in code/web rather than code/).

Specifically, I followed the Pantheon guide here:
https://pantheon.io/docs/guides/github-pull-requests/
And the guide for modifying kalabox to use this workflow here:
https://www.thinktandem.io/blog/2017/05/20/using-pantheon-s-nested-docroot-with-kalabox/

The main issue is that in this repo layout:

* The site code is in code/web
* Tests are stored in code/tests/features
* behat.yml is in code/tests

So, to get the plugin to work with this layout, in the plugin's behat-compose.yml, I changed the following:
    - $KALABOX_APP_ROOT/code/web:/srv/code
    - $KALABOX_APP_ROOT/code/tests/behat.yml:/srv/behat.yml
    - $KALABOX_APP_ROOT/code/tests/features:/srv/features

I then moved behat.yml from /code to /code/tests.

However, after restarting kalabox, I am now getting this error:
Fatal error: Class 'Drupal\Core\Session\AccountInterface' not found in /srv/code/core/includes/bootstrap.inc on line 63

I will continue to troubleshoot this myself but if you have any suggestions about how to fix this they would be much appreciated.

**Comment by leevh** [comment]
hey @ptmkenny , honestly I probably won't get any time to look into this plus I've moved over to using Lando instead now that its stable enough (behat is super easy to hookup too).  PR's are always welcome though

**Comment by ptmkenny** [comment]
@leevh Ok, thanks for letting me know!  I'm trying out Lando now.
